server:
  port: 8080

spring:
  datasource:
    username: root
#    password: 130324yhc
#    username: crowdos
    password: EqCvN3FP
    url: jdbc:mysql://47.96.146.104:3306/zph?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: team.crowdos.crowdsharing.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
